export const COMMANDS = {
	SHOW_GENERATE_COMMIT_BUTTON: 'gonext.show-generate-commit-button',
	GENERATE_COMMIT_MESSAGE: 'gonext.generate-commit-message',
	SHOW_SETTINGS: 'gonext.show-settings',
	SHOW_CODELENS_QUICKPICK: 'gonext.show-codelens-quickpick',
	SHOW_SIDEBAR: 'gonext.show-sidebar',
	SHOW_CODE_INSTRUCTION_INPUT: 'gonext.show-code-instruction-input',
	SIDEBAR_NEW_CHAT: 'gonext.sidebar.new-chat',
	SIDEBAR_SHOW_HISTORY: 'gonext.sidebar.show-history',
	SIDEBAR_SHOW_SETTINGS: 'gonext.sidebar.show-settings',
	SIDEBAR_RESET: 'gonext.sidebar.reset',
	SHOW_WALKTHROUGH: 'gonext.show-walkthrough',
	INLINE_DOCUMENT: 'gonext.inline-document',
	INLINE_DOCUMENT_ACCEPT: 'gonext.inline-document-accept',
	INLINE_DOCUMENT_REJECT: 'gonext.inline-document-reject',
	EXPLAIN_PROBLEM: 'gonext.explain-problem',
	CONTEXT_MENU_EXPLAIN: 'gonext.context-menu.explain',
	CONTEXT_MENU_OPTIMIZE: 'gonext.context-menu.optimize',
	// Flow commands
	CREATE_FLOW: 'gonext.flow.create',
	PAUSE_FLOW: 'gonext.flow.pause',
	RESUME_FLOW: 'gonext.flow.resume',
} as const;