export const INJECTION_KEYS = {
    CONTEXT: Symbol('CONTEXT'),
    COMMAND_REGISTRY: Symbol('COMMAND_REGISTRY'),
    PROVIDER_FACTORY: Symbol('PROVIDER_FACTORY'),
    SIDEBAR_PROVIDER: Symbol('SIDEBAR_PROVIDER'),
    CONTEXT_MANAGER: Symbol('CONTEXT_MANAGER'),
    // Flow services
    FLOW_STATE_MANAGER: Symbol('FLOW_STATE_MANAGER'),
    FLOW_EXECUTOR: Symbol('FLOW_EXECUTOR'),
    FLOW_SERVICE: Symbol('FLOW_SERVICE'),
} as const;