export const INJECTION_KEYS = {
    CONTEXT: Symbol('CONTEXT'),
    COMMAND_REGISTRY: Symbol('COMMAND_REGISTRY'),
    PROVIDER_FACTORY: Symbol('PROVIDER_FACTORY'),
    GONEXT_SERVICE: Symbol('GONEXT_SERVICE'),
    SIDEBAR_PROVIDER: Symbol('SIDEBAR_PROVIDER'),
    CODE_LENS_PROVIDER: Symbol('CODE_LENS_PROVIDER'),
    INLINE_COMPLETION_ITEM_PROVIDER: Symbol('INLINE_COMPLETION_ITEM_PROVIDER'),
    INLINE_SUGGESTION_CODE_LENS_PROVIDER: Symbol('INLINE_SUGGESTION_CODE_LENS_PROVIDER'),
    COMPLETION_PROVIDER: Symbol('INLINE_COMPLETION_PROVIDER'),
    QUICK_FIX_PROVIDER: Symbol('QUICK_FIX_PROVIDER'),
    CONTEXT_MANAGER: Symbol('CONTEXT_MANAGER'),
    // Flow services
    FLOW_STATE_MANAGER: Symbol('FLOW_STATE_MANAGER'),
    FLOW_EXECUTOR: Symbol('FLOW_EXECUTOR'),
    FLOW_SERVICE: Symbol('FLOW_SERVICE'),
    AI_CLIENT: Symbol('AI_CLIENT'),
} as const;