export enum SidebarInputCommands {
    FLOW_LIST_UPDATE = "FLOW_LIST_UPDATE",
    FLOW_STATE_CHANGE = "FLOW_STATE_CHANGE",
    FLOW_PROGRESS_UPDATE = "FLOW_PROGRESS_UPDATE",
    FLOW_BLUEPRINT_GENERATED = "FLOW_BLUEPRINT_GENERATED",
    FLOW_ERROR = "FLOW_ERROR"
};

export enum SidebarOutputCommands {
    CREATE_FLOW = "CREATE_FLOW",
    GET_FLOWS = "GET_FLOWS",
    SEARCH_FLOWS = "SEARCH_FLOWS",
    GENERATE_FLOW_BLUEPRINT = "GENERATE_FLOW_BLUEPRINT",
    START_FLOW_EXECUTION = "START_FLOW_EXECUTION",
    PAUSE_FLOW_EXECUTION = "PAUSE_FLOW_EXECUTION",
    STOP_FLOW_EXECUTION = "STOP_FLOW_EXECUTION",
    DELETE_FLOW = "DELETE_FLOW",
    RENAME_FLOW = "RENAME_FLOW",
    OPEN_FLOW_DETAILS = "OPEN_FLOW_DETAILS"
};
