export enum InputCommands {
    SYNC_CONFIG = "SYNC_CONFIG",
    SYNC_CODEBASE = "SYNC_CODEBASE",
    SYNC_FILE_INFO = "SYNC_FILE_INFO",
    NEW_CHAT = "NEW_CHAT",
    OPEN_HISTORY = "OPEN_HISTORY",
    RESET = "RESET",
    SHOW_SIDEBAR_SETTINGS = "SHOW_SIDEBAR_SETTINGS",
    STREAM_RESPONSE = "STREAM_RESPONSE",
    FETCH_MODELS_RESPONSE = "FETCH_MODELS_RESPONSE",
    GET_CONVERSATION_TITLE_RESPONSE = "GET_CONVERSATION_TITLE_RESPONSE",
    // Flow commands
    FLOW_LIST_UPDATE = "FLOW_LIST_UPDATE",
    FLOW_CREATED = "FLOW_CREATED",
    FLOW_UPDATED = "FLOW_UPDATED",
    FLOW_DELETED = "FLOW_DELETED",
    FLOW_ERROR = "FLOW_ERROR"
};

export enum OutputCommands {
    SYNC_REQUEST = "SYNC_REQUEST",
    STREAM_REQUEST = "STREAM_REQUEST",
    GENERATE_BLUEPRINT = "GENERATE_BLUEPRINT",
    START_AGENT = "START_AGENT",
    RUN_COMMAND = "RUN_COMMAND",
    INSERT_CODE = "INSERT_CODE",
    SHOW_ALERT = "SHOW_ALERT",
    FETCH_MODELS = "FETCH_MODELS",
    UPDATE_APP_CONFIG = "UPDATE_APP_CONFIG",
    EDIT_FILE = "EDIT_FILE",
    GET_CONVERSATION_TITLE = "GET_CONVERSATION_TITLE",
    STOP_STREAM = "STOP_STREAM",
    DOWNLOAD_MODEL = "DOWNLOAD_MODEL",
    DELETE_LOCAL_MODEL = "DELETE_LOCAL_MODEL",
    // Flow commands
    CREATE_FLOW = "CREATE_FLOW",
    GET_FLOWS = "GET_FLOWS",
    SEARCH_FLOWS = "SEARCH_FLOWS",
    GENERATE_FLOW_BLUEPRINT = "GENERATE_FLOW_BLUEPRINT",
    START_FLOW_EXECUTION = "START_FLOW_EXECUTION",
    PAUSE_FLOW_EXECUTION = "PAUSE_FLOW_EXECUTION",
    STOP_FLOW_EXECUTION = "STOP_FLOW_EXECUTION",
    DELETE_FLOW = "DELETE_FLOW",
    RENAME_FLOW = "RENAME_FLOW",
    OPEN_FLOW_DETAILS = "OPEN_FLOW_DETAILS"
};
